# Generated by Django 3.0.3 on 2020-03-23 14:06

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date of start')),
                ('event', models.CharField(max_length=150)),
                ('best_of', models.CharField(max_length=15)),
                ('match_id', models.IntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('has_ended', models.BooleanField(default=False)),
                ('streams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('maps_played', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('team_id', models.IntegerField(default=0)),
                ('logo', models.CharField(max_length=300)),
                ('rank', models.IntegerField(default=0, null=True)),
                ('avg_age', models.FloatField(default=0, null=True)),
                ('winrate', models.FloatField(default=0, null=True)),
                ('last_matches', jsonfield.fields.JSONField()),
                ('match', models.ManyToManyField(to='ollo_cs.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=40, null=True)),
                ('real_name', models.CharField(max_length=100, null=True)),
                ('team_logo_bg', models.CharField(max_length=150, null=True)),
                ('avatar', models.CharField(max_length=150, null=True)),
                ('rating', models.FloatField(default=0)),
                ('headshots', models.FloatField(default=0)),
                ('kpr', models.FloatField(default=0)),
                ('dpr', models.FloatField(default=0)),
                ('maps', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ollo_cs.Team')),
            ],
        ),
        migrations.CreateModel(
            name='IndexMatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_score', models.IntegerField(default=0)),
                ('ct_score', models.IntegerField(default=0)),
                ('t_name', models.CharField(max_length=60)),
                ('ct_name', models.CharField(max_length=60)),
                ('terrorists', jsonfield.fields.JSONField(default=None)),
                ('counter_terrorists', jsonfield.fields.JSONField(default=None)),
                ('map_name', models.CharField(default='no map', max_length=40)),
                ('current_round', models.IntegerField(default=0)),
                ('bomb_planted', models.BooleanField(default=False)),
                ('round_time_delta', models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 8, 16, 632671, tzinfo=utc))),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='ollo_cs.Match')),
            ],
        ),
    ]
