# Generated by Django 3.0.3 on 2020-03-23 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ollo_cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmatchinfo',
            name='round_time_delta',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 11, 5, 998917, tzinfo=utc)),
        ),
    ]
