# Generated by Django 3.0.3 on 2020-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollo_cs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
