# Generated by Django 3.0.3 on 2020-03-23 20:17

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ollo_cs', '0002_auto_20200323_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmatchinfo',
            name='round_time_delta',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 20, 19, 15, 971706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='match',
            name='streams',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None), size=None),
        ),
    ]
