# Generated by Django 3.0.3 on 2020-03-12 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ollo_cs', '0002_auto_20200311_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmatchinfo',
            name='round_time_delta',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 8, 27, 49, 393341, tzinfo=utc)),
        ),
    ]
